### ISSUE TITLE
物体のポイントクラウドで手前のポイントしか見つからない？

### ISSUE THREAD

**Issue by ban-masa** [start-jsk/jsk_apc#1813]
bin-overlook-pose ？　で手前のポイントしかみつからなくなにか困っている ？　@pazeshun 
だっけ？問題を教えてください。
@wkentaro が直してくれます

by @k-okada

**Comment by pazeshun** [comment]
はい、カメラを平行に近づけて見ると、Binの奥の物品のポイントクラウドまで取れるのですが、各物品の手前の面しかポイントがとれず、逆にカメラを角度つけてみると、手前の物品の上の面のポイントが取れるようになるけど、奥が見えないということがおきていました。

**Comment by pazeshun** [comment]
また、それとは全く別の問題として、生のポイントクラウドが結構少なめな気がしていて、RGBカメラ画像にしっかり写っている物品の点群が全くとれていないということがありました。

**Comment by k-okada** [comment]
なるほど
これは
ポイントクラウド->セグメンテーション->各物品の中心(重心？把持位置)
というかんじかな？

たとえば微妙に角度をかえて10回ぐらい処理して一番いいやつを使うようなことはできるのかな？
一番良いの定義ができるか、ですが、いいときは結果が出て良くないときは結果が出ないとすると、これでいいわけだけど



2016年6月26日日曜日、pazeshun<notifications@github.com>さんは書きました:

>
> はい、カメラを平行に近づけて見ると、Binの奥の物品のポイントクラウドまで取れるのですが、各物品の手前の面しかポイントがとれず、逆にカメラを角度つけてみると、手前の物品の上の面のポイントが取れるようになるけど、奥が見えないということがおきていました。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1813#issuecomment-228584595>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3MffPHdvFFFItp6nIhFRNjQIdWIyks5qPgjUgaJpZM4I-fHj>
> .
>


-- 
--
◉ Kei Okada

**Comment by k-okada** [comment]
> 生のポイントクラウドが結構少なめな気がしていて、

Depth画像を見てみましょう

2016年6月26日日曜日、pazeshun<notifications@github.com>さんは書きました:

>
> また、それとは全く別の問題として、生のポイントクラウドが結構少なめな気がしていて、RGBカメラ画像にしっかり写っている物品の点群が全くとれていないということがありました。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1813#issuecomment-228584653>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3IGfGBbMu0HIP0rKLSqsCtm5tlJuks5qPgldgaJpZM4I-fHj>
> .
>


-- 
--
◉ Kei Okada

**Comment by pazeshun** [comment]
Depth画像というのは、2Dで出てくるもののことでしょうか？
見たんですが、結果がよくわかりませんでした。
私が主にみたポイントクラウドはrviz上の3D表示です

**Comment by pazeshun** [comment]
角度変えるプログラムは、パッキング終わったら書こうと思ってます

**Comment by k-okada** [comment]
> Depth画像というのは、2Dで出てくるもののことでしょうか？

はい。画面のキャプチャでいいので撮ってみてください。



2016年6月26日日曜日、pazeshun<notifications@github.com>さんは書きました:

> 角度変えるプログラムは、パッキング終わったら書こうと思ってます
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1813#issuecomment-228585040>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3DRangNxckTSDYqlOqMXNUPlP-i3ks5qPg0fgaJpZM4I-fHj>
> .
>


-- 
--
◉ Kei Okada

**Comment by pazeshun** [comment]
すいません、今家なので、どなたかキャプチャお願いします

**Comment by yuyu2172** [comment]
depth 
![rviz_screenshot_2016_06_26-15_52_47](https://cloud.githubusercontent.com/assets/2062128/16360913/1998bcda-3bb6-11e6-9ecd-63297e9bd85c.png)

rgb
![frame0000](https://cloud.githubusercontent.com/assets/2062128/16360915/2e5aa232-3bb6-11e6-8d01-a6a5c543d29e.jpg)


pointcloud
![pcl](https://cloud.githubusercontent.com/assets/2062128/16360919/52c480de-3bb6-11e6-8d39-05bc49facfd9.png)

**Comment by yuyu2172** [comment]
The camera can capture depth points depending on arm position.

depth 
![frame0000](https://cloud.githubusercontent.com/assets/2062128/16361096/0eec4182-3bbe-11e6-889b-4d5efa14a0b5.jpg)

rgb
![frame0000](https://cloud.githubusercontent.com/assets/2062128/16361097/1da8392e-3bbe-11e6-8d2c-d38f86dd03f0.jpg)

**Comment by pazeshun** [comment]
@yuyu2172 カメラで見るのによい位置を探して、そのときの見ているBinとロボットの関節角度を教えてくれるとうれしいです。
ロボットの関節角度は`/robot/joint_states`をsubscribeしたものでよいので。

**Comment by yuyu2172** [comment]
For `bin_L`, a desirable joint angles are 

```
header:
  seq: 166243
  stamp:
    secs: 1466934127
    nsecs: 929186231
  frame_id: ''
name: ['head_nod', 'head_pan', 'left_e0', 'left_e1', 'left_s0', 'left_s1', 'left_w0', 'left_w1', 'left_w2', 'right_e0', 'right_e1', 'right_s0', 'right_s1', 'right_w0', 'right_w1', 'right_w2', 'torso_t0']
position: [0.0, 0.003451456772742181, -1.6478788613859057, 2.350058567040454, 1.7008011985679525, -0.04141748127290617, 1.5957235145978017, 0.16260196351585385, 0.0, 1.8634031620838063, 2.350058567040454, -0.31408256631953846, 0.29260683528914266, 0.6412039693361029, -1.5274613695369008, -2.106155621766673, -12.565987119160338]
velocity: [0.0, -0.014137166938502187, -0.00039269908162506076, -0.0070685834692510935, -0.007853981632501214, -0.003926990816250607, -0.01021017612225158, -0.007853981632501214, 0.0047123889795007284, -0.0070685834692510935, 0.012173671530376884, -0.00039269908162506076, 0.0019634954081253035, 0.0011780972448751821, -0.019242254999627974, 0.008246680714126275, 0.0]
effort: [0.0, 0.0, -21.992, -1.052, 0.996, 10.068, 1.044, -4.336, 0.576, 21.18, 0.968, -0.184, 3.072, -2.82, 1.68, -0.56, -20.48]
```

I move to this position using following eus code.
```
send *ri* :ik->bin-entrance :rarm :l :offset #f(-280 0 20) :rotation-axis t :overlook-angle (/ pi 5)
```
